name: noticia_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  provider: ^6.1.2
  dio: ^5.0.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  webview_flutter_web: ^0.2.3+2
  cached_network_image: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/sol.jpg
    - assets/montanha.jpg
    - assets/piza.jpg
    - assets/logo_g1.png
    - assets/logo_record.png
    - assets/logo_cnn.png

