// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt58DEcK0K2bxq3YwC_DLjYwGmsodVl5A',
    appId: '1:1016871516311:web:147e72731a3c584c3d11d2',
    messagingSenderId: '1016871516311',
    projectId: 'noticia-16301',
    authDomain: 'noticia-16301.firebaseapp.com',
    storageBucket: 'noticia-16301.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmEr2EnsGiLgP2bn_iet627ho4rNKJbk',
    appId: '1:1016871516311:android:a91e680bcddf14693d11d2',
    messagingSenderId: '1016871516311',
    projectId: 'noticia-16301',
    storageBucket: 'noticia-16301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK-Pdk6c0TRFNuDb1suI9Mr4UgxcIk1Ok',
    appId: '1:1016871516311:ios:1391aa68dea0d2553d11d2',
    messagingSenderId: '1016871516311',
    projectId: 'noticia-16301',
    storageBucket: 'noticia-16301.appspot.com',
    iosBundleId: 'com.example.noticiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK-Pdk6c0TRFNuDb1suI9Mr4UgxcIk1Ok',
    appId: '1:1016871516311:ios:1391aa68dea0d2553d11d2',
    messagingSenderId: '1016871516311',
    projectId: 'noticia-16301',
    storageBucket: 'noticia-16301.appspot.com',
    iosBundleId: 'com.example.noticiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt58DEcK0K2bxq3YwC_DLjYwGmsodVl5A',
    appId: '1:1016871516311:web:6777ca26e3c700d73d11d2',
    messagingSenderId: '1016871516311',
    projectId: 'noticia-16301',
    authDomain: 'noticia-16301.firebaseapp.com',
    storageBucket: 'noticia-16301.appspot.com',
  );
}
